[Definition]

actionban = curl \
  -H "Title: 🚫 Fail2ban: IP Banned" \
  -H "Priority: low" \
  -H "Tags: shield,warning" \
  -H "Markdown: yes" \
  -d "$(printf '**IP:** <ip>\n**Jail:** <name>\n**Failures:** <failures> attempts\n**Action:** IP blocked')" \
  https://ntfy.sh/xxxxxxxxxx

actionunban = curl \
  -H "Title: 🔓 Fail2ban: IP Unbanned" \
  -H "Priority: low" \
  -H "Tags: white_check_mark" \
  -H "Markdown: yes" \
  -d "$(printf '**IP:** <ip>\n**Jail:** <name>\n**Status:** Ban expired, IP unblocked.')" \
  https://ntfy.sh/xxxxxxxxxx



[Init]

name = default
